### ISSUE TITLE
Invalid error thrown when scanning a QR Code to Create an Account

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-ios#16]
When scanning a QR code from one wallet to the under, for the “Create Account” functionality, it doesn’t recognize the QR code upon scanning, but it does scan it (the public key gets accurately filled into the field). 
 
![Screen Shot 2019-09-11 at 10 09 23 AM](https://user-images.githubusercontent.com/42808726/64704478-5d6d7b00-d47c-11e9-87a7-f5a70da02b26.png)

**Comment by avichalsaxena** [comment]
Tested on 129 build. Working perfectly.
