### ISSUE TITLE
As we can clearly see from the screenshot below, only hbar is shown. Dollar value is hidden for some reason.

### ISSUE THREAD

**Issue by avichalsaxena** [hashgraph/hedera-wallet-ios#170]
![Simulator Screen Shot - iPhone 11 - 2019-10-30 at 10 43 26](https://user-images.githubusercontent.com/40248431/67868298-29b8e400-fb02-11e9-806f-e4bcea60f78c.png)

**Comment by sreejithkaimal** [comment]
@donaldthibeau We need to discuss this problem. The record has a bunch of transfers, @surendrapatidar is picking the max transfer & showing it. Should be add it as service fee & node fee ?

**Comment by donaldthibeau** [comment]
We should show a single value which includes the transfer and fee if they paid for the transfer. If they are the receiving account, then I think it should just show the amount received.

**Comment by sreejithkaimal** [comment]
@donaldthibeau that would be a complex logic, we will track it for next release. 
```
"transfers": [
      {
        "accountID": {
          "num": 1002,
          "shardNum": 0,
          "realmNum": 0
        },
        "amount": -251531
      },
      {
        "accountID": {
          "num": 3,
          "shardNum": 0,
          "realmNum": 0
        },
        "amount": 15334
      },
      {
        "accountID": {
          "num": 98,
          "shardNum": 0,
          "realmNum": 0
        },
        "amount": 236197
      },
      {
        "accountID": {
          "num": 1002,
          "shardNum": 0,
          "realmNum": 0
        },
        "amount": -2528
      },
      {
        "accountID": {
          "num": 98,
          "shardNum": 0,
          "realmNum": 0
        },
        "amount": 2528
      },
      {
        "accountID": {
          "num": 1002,
          "shardNum": 0,
          "realmNum": 0
        },
        "amount": -25
      },
      {
        "accountID": {
          "num": 3,
          "shardNum": 0,
          "realmNum": 0
        },
        "amount": 25
      }
    ],
```
here we should show the total deducted from the account only ?

**Comment by donaldthibeau** [comment]
Yes, ultimately the user should see the total of what is withdrawn or deposited.

**Comment by avichalsaxena** [comment]
171 is taking care of this. Closing this for now.
