### ISSUE TITLE
Account transfer fee listed in records was MAX FEE, not actual fee

### ISSUE THREAD

**Issue by robert-at-hedera** [hashgraph/hedera-wallet-ios#177]
Note that refreshing the transactions with get records does not resolve this.

Reproduction steps:
1. Load up an account
2. Make a transfer to a different account
3. Get transaction records
4. Refresh account information
5. Look at transfer record for step 2
Expected result: the fee listed is the amount charged
Actual result: the fee listed is the maximum allowed fee transmitted to the network

**Comment by avichalsaxena** [comment]
Please test this on main-net. The fee deducted for me is 0.00254033 hBar not the max fee of 0.5 hBar.

**Comment by avichalsaxena** [comment]
I am able to reproduce this. This should happen on Android and iOS both. When you do a transfer and check the fee deducted, it shows the max fee. The fee gets updated only after a getRecords is pressed. Therefore we get the correct fee only after doing a getRecords and there is no other way to get the actual fee before. We can either show that the fee = NA if that clears the confusion.

**Comment by robert-at-hedera** [comment]
The behavior you described is what I expected, Avichal.  This was not happening, but due to an error on my part (not the app).

The fee information was not being updated due to no transaction / query being reported by the node due to being below threshold.  The test account was created by the web portal (see #176).  Closing as not a bug.

Thanks for taking the time to explain your expectations to help me determine the error on my end!
