### ISSUE TITLE
Rename "Styrene H" fonts to "Hedera H"

### ISSUE THREAD

**Issue by robert-at-hedera** [hashgraph/hedera-wallet-ios#180]
Please go through the font folder and rename the Styrene H fonts to Hedera H, then update the usage of fonts in the application to match the new name.

**Comment by avichalsaxena** [comment]
Does this override #159 ?

**Comment by robert-at-hedera** [comment]
No, they both need to be done.  Styrene A, a real font, gets updated to a new file which has the correct license in it. (#159)  Styrene H, which is a "font" with only the HBAR character, isn't by the guy who designed Styrene A.  So we need to rename Styrene H so people don't think he drew it (this issue).

Does that clarify, Avichal?

**Comment by avichalsaxena** [comment]
Yes, thank you @robert-at-hedera !

**Comment by avichalsaxena** [comment]
Referenced in the latest commit
