### ISSUE TITLE
Unit Test Setup - Application Internals & Settings

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-ios#26]
Internals & Settings

1. Database setup 
When the application is built, check if the local database is setup correctly, the following test cases should be executed

- Any new tables /schema / fields that will cause migration problem in application.
- Any OS specific setting that will cause problems
- Any constraints on locale, language or region

2. Configuration is ready (dev vs prod)

- A dev build should result in the right node configuration, app name and other settings.
- Automatic build based on a script or command line.

3. Package, property files & Assets
- Check if the property files, resources, assets are present for the required builds
- Check if the values of constants/files/codes are populated.
- Version checks
- Developer Certs for CI-CD

Evaluate CircleCI for doing automated builds.

**Comment by avichalsaxena** [comment]
duplicate with #155
