### ISSUE TITLE
List library licenses

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-ios#28]
Libraries used by the app under the MIT, Apache, and similar licenses require attribution.  This needs to happen "in" the release, which is where these libraries actually are used.  A license screen accessible from the about screen is sufficient for the latter.

The task is to go through the iOS app and determine what libraries are used.  Gather the licenses and put them into a text file.  Then add a button to the about screen linking to a new license screen which simply displays the text file.

**Comment by robert-at-hedera** [comment]
Not merging this until I speak with legal tomorrow.

**Comment by robert-at-hedera** [comment]
Putting this on hold for now.
