### ISSUE TITLE
Hedera Wallet crashes for a user when they click “Recovery Phrase”

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-wallet-ios#285]
Hedera Wallet crashes for a user when they click “Recovery Phrase”
Account ID in question - https://app.dragonglass.me/hedera/accounts/0.0.9218

Public Key for account on Dragon Glass does not look the same
![WhatsApp Image 2020-05-13 at 23 12 01](https://user-images.githubusercontent.com/13358210/82218335-5f2bf000-98e1-11ea-9ef1-89dd3e66f30d.jpeg)
![WhatsApp Image 2020-05-13 at 23 34 30](https://user-images.githubusercontent.com/13358210/82218339-605d1d00-98e1-11ea-949a-b90974ca868d.jpeg)

**Comment by donaldthibeau** [comment]
Please intro me to the user for resolution.

**Comment by donaldthibeau** [comment]
If a user is experiencing crashes using the wallet, they should migrate to an option such as MyHBARWallet using their recovery words.

**Comment by fakepaulbugeja** [comment]
I introduced James to Donald & he responded with the following:

_Hi Donald,

I was able to solve the issue by doing a 'Master Reset'. I noticed that several people mentioned on Discord and Telegram that they had similar issues after the latest update on IOS. Prior to the reset, the app was closing every time I attempted to view the recovery phrase or privacy key. I did not try myself, but other users mentioned they were unable to make transactions.

I wanted to double check my recovery phrase prior to the master reset as the app had displayed a different recovery phrase once when I attempted to view it. The phrase was the word 'words' written 24 times. I assumed this was just a default variable value when the phrase could not be returned.

That is pretty much everything, but happy to chat if you need to ask any further questions.

Regards,
James_

**Comment by anighanta** [comment]
Hi Guys, Im trying to recreate the scenario on my own apple device and on my Xcode simulation of our wallet app. 

I tried the following scenarios
1. On my existing wallet which has an account already linked, I tried clicking on `Recovery Phrase` the app didn't crash
2. One my existing wallet I did a `Master Reset` and crated a new Wallet account and then tried clicking on `Recovery Phrase`. The app didn't crash.
3. I tried the same scenarios on the Xcode simulation and the app is stable there as well in both in Debug mode and Release mode using the latest code for the wallet aap.

The version I have on my apple device is 1.4.136 Build 136

If I'm missing a step in the above scenarios please let me know and I can re do them and see if I can reproduce.

**Comment by fakepaulbugeja** [comment]
Hey @anighanta, @donaldthibeau stated the below previously:

_depending on if the user has configured cloud backup they may experience the issue._

**Comment by anighanta** [comment]
Successfully Recreated the issue locally while debugging. When the app can't get the seed [ I created a trap method that only returns null when asked for a seed ] app crashes. I understand now why this is not observed on all cases.

**Comment by fakepaulbugeja** [comment]
Hi @anighanta, @donaldthibeau, please see the **attached** video. The user is unable to:

- Inspect their seed
- Inspect their private key
- Send funds to another account

As we seem to know why this is occuring (https://github.com/hashgraph/hedera-wallet-ios/issues/287), could we push an unpdate to resolve?

[RPReplay_Final1590700846.zip](https://github.com/hashgraph/hedera-wallet-ios/files/4700417/RPReplay_Final1590700846.zip)
