### ISSUE TITLE
Handle missing Seed.

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-wallet-ios#287]
Fix for https://github.com/hashgraph/hedera-wallet-ios/issues/285

To handle a missing seed [ right now not digging into the cause of the issue], 
planned approach is to pop up a window with a warning message [ provided by @donaldthibeau ] and Ok button which when clicked would redirect to home page.

@donaldthibeau do you think this is approach is fair enough ?

**Comment by donaldthibeau** [comment]
Messaging: "Please attempt to recover your Hedera Account using the recovery phrases."
