### ISSUE TITLE
Wallet crashes, unable to export private key & seed phrase

### ISSUE THREAD

**Issue by niels-glitch** [hashgraph/hedera-wallet-ios#297]
Experiencing serious issues with the official Hedera Wallet on both of my phones. 

I can not currently send any transaction from both wallets. As soon as I press 'Pay', the app crashes. 

My idea was then to export the private keys/memory phrase, but when I do that, the app automatically crashes too:
1) When I  go to the Recovery Phrase section from the Menu, I get a popup:
‘Please attempt to recover your Header Account using the recovery phrase’
2)  When I click Display Private Key, I first get a popup if I really want to display it. When I press YES, the app automatically closes.

In short, I’m fully unable to do anything with my account, and I can't export any info that will help me access the wallet somewhere else. I have the app installed on both of my phones, and the same issue on both. 

There is a difference however:
Phone 1  (iOS) runs 1.4.169 on the App, and DOES NOT feature the Update Key option in the menu
Phone 2 (iOS, but older phone) runs 1.4.138 of the App, and DOES feature the Update Key option in the menu. However, according to [this article](https://help.hedera.com/hc/en-us/articles/360002405738-Why-is-my-Hedera-Wallet-asking-me-to-update-my-public-private-key-pair-and-backup-phrase-), I should not do this until I can confirm my original private keys are working. However, the seed phrase that I used when I set up my account does not work.

There are significant funds in the wallets, how can I export my personal data from it? 

Some more notes, of which I do not know if they're useful:
- The latest successful outgoing transaction was done on June 9. Likely, one of the last updates broke the wallet for me.
- I have done KYC through Hedera Portal, it is associated with my account.
- I have screen recordings for behavior on both phones.

**Comment by richbybits** [comment]
I am still facing the same issue, I tried recovering the wallet at myhbarwallet.com using my mnemonic phrase, it says the account ID is not valid for the key. Even the public key is different. All our funds are just on the screen. Not able to utilize them.

**Comment by shadowfresh** [comment]
I am having the same issue. Has there been any resolution to this particular issue? 

> I am still facing the same issue, I tried recovering the wallet at myhbarwallet.com using my mnemonic phrase, it says the account ID is not valid for the key. Even the public key is different. All our funds are just on the screen. Not able to utilize them.

**Comment by richbybits** [comment]
I resolved the issue, the problem was in Face ID recognition with the app. Hope they correct it. I imported the wallet to my old iPhone with a fingerprint scanner. From there I sent it to hbarwallet. For every wallet activation 1 HBAR is charged.

**Comment by richbybits** [comment]
Also there was a new seed phrase sometime early this year for the wallet upgrade. If upgraded using that may help.

**Comment by tomasgulas** [comment]
I'm facing the same issue, the app crashes while I try to access the private key or send funds, the build I'm using is 169 on iPhone 8. I can't export recovery phrase nor the private key. After the app update the public key was changed and my recovery phrase doesn't work. I can only display available balance on my account but can't access it at all. @anighanta can you please look into this?

**Comment by mraza21** [comment]
Hi

I have the same issue, I am not able to verify my account id with recovery pharse and almost have 2000 hbars in wallet on my iso phone. Any suggestion to resolve this issue? I tried hedera community but they dont have much knowledge 
I am losing big time here. I can see my account growing but can't move my hbars to any exchange or different wallet

**Comment by ctapang** [comment]
My sister is having the same issue. Glad to know we are not alone. How many other users are affected?

**Comment by donaldthibeau** [comment]
Please send all recovery related issues to support@hedera.com

**Comment by ctapang** [comment]
Please check out my post in reddit.com - if victims of this bug work together, we can make Hedera be more responsible.

![image](https://user-images.githubusercontent.com/2825510/115598404-406f6f80-a28f-11eb-93f4-6115fff03f8e.png)
