### ISSUE TITLE
Tag IOS Wallet Releases

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-wallet-ios#299]
Version | Commit Id
------------ | -------------
1.4.170 | [cbf65c547b4791cfc7f2bb3fa8abcb678db4dc4a](https://github.com/hashgraph/hedera-wallet-ios/pull/298/commits/cbf65c547b4791cfc7f2bb3fa8abcb678db4dc4a)
1.4.138 | [cd2878a732fb05f5fe82e01dd566db50014b3632](https://github.com/hashgraph/hedera-wallet-ios/commit/cd2878a732fb05f5fe82e01dd566db50014b3632)
1.4.136 | [801a8689ee023ec76a7f29eb51dd8d3af55ed0ee](https://github.com/hashgraph/hedera-wallet-ios/pull/289/commits/801a8689ee023ec76a7f29eb51dd8d3af55ed0ee)
1.3.131 | [d7b4942c9a608224796f4e0248c8997871b532c5](https://github.com/hashgraph/hedera-wallet-ios/pull/274/commits/d7b4942c9a608224796f4e0248c8997871b532c5)
1.3.129 | [0ea6e69876bbfd0c6b218c3c3bdaa3a3074270c9](https://github.com/hashgraph/hedera-wallet-ios/commit/0ea6e69876bbfd0c6b218c3c3bdaa3a3074270c9)
1.2.124 | [8f8a5b5681be148ee6df536f8838192d7bdfcd58](https://github.com/swirlds/clients-hedera/commit/8f8a5b5681be148ee6df536f8838192d7bdfcd58)
1.2.118 | 
1.2 | [12827d6af5a34fcb7678237cb1e1f2e3cc6bb2dd](https://github.com/swirlds/clients-hedera/commit/12827d6af5a34fcb7678237cb1e1f2e3cc6bb2dd#diff-48ee046028069a9c6ded9844911eab9020389ac067e2a8772244b99be182e063)
1.1.1 | [fa34c9d0f5801b3378facd457959ee8252792742](https://github.com/swirlds/clients-hedera/commit/fa34c9d0f5801b3378facd457959ee8252792742#diff-48ee046028069a9c6ded9844911eab9020389ac067e2a8772244b99be182e063)
1.1.0 | [5248bd689342fea5e4699da6d30e9f5ef7215d7b](https://github.com/swirlds/clients-hedera/commit/5248bd689342fea5e4699da6d30e9f5ef7215d7b#diff-48ee046028069a9c6ded9844911eab9020389ac067e2a8772244b99be182e063)
1.0.3 | [d727eb4a49c1bb88477ad0bd88ef882690055777](https://github.com/swirlds/clients-hedera/commit/d727eb4a49c1bb88477ad0bd88ef882690055777#diff-48ee046028069a9c6ded9844911eab9020389ac067e2a8772244b99be182e063)
1.0.2 | [82ce65e1eda6a8a02258d04706794f9978cee126](https://github.com/swirlds/clients-hedera/commit/82ce65e1eda6a8a02258d04706794f9978cee126)
1.0.1 | [82ce65e1eda6a8a02258d04706794f9978cee126](https://github.com/swirlds/clients-hedera/commit/82ce65e1eda6a8a02258d04706794f9978cee126#diff-48ee046028069a9c6ded9844911eab9020389ac067e2a8772244b99be182e063)

**Comment by anighanta** [comment]
@kenthejr @donaldthibeau Im gonna tag these commits respectively with their release versions. Let me know if I need to change anything.

**Comment by donaldthibeau** [comment]
Looks good to me.

**Comment by anighanta** [comment]
Done tagging.
repo - [hedera-wallet-ios](https://github.com/hashgraph/hedera-wallet-ios/tags)
repo - [clients-hedera](https://github.com/swirlds/clients-hedera/tags)
