### ISSUE TITLE
I AM NOT ABLE TO TRANSFER MY HBARS TO DIFFERENT WALLET

### ISSUE THREAD

**Issue by mraza21** [hashgraph/hedera-wallet-ios#303]
Hi

I am not able to verify my account id with recovery pharse whenever i will try to update my wallet on my iphone and almost have 2000 hbars in my wallet . Any suggestion how to resolve this issue? I tried hedera community but they dont have much knowledge how to resolve it. My account id is 0.0.3876 on hedera mainnet.
I am losing big time here. I can see my account growing but can't move my hbars to any exchange or different wallet.
Please help me with this issue!!
I will be really grateful

**Comment by ctapang** [comment]
My sister is having the same issue. She recorded the 24-word mnemonic on a piece of paper but there's something wrong with th mnemonic. It's very unlikely that she made a mistake in copying the 24-word mnemonic. Her account ID is 0.0.11694
Help!

**Comment by mraza21** [comment]
I Tried Hedera discord community but looks like nobody is here to help. I thing its a lost call

**Comment by ctapang** [comment]
I don't think it's a lost cause if there is indeed a problem with the Hedera wallet and there are many investors affected. Let's look for other people who have lost money because of the issue. There is a company / organization behind Hedera that can be liable if they just ignore the issue. Hedera is not a "blockchain" like Bitcoin, both in the technical sense and legal sense.

**Comment by ctapang** [comment]
Just posted the following in reddit. You may post a similar message in other social media:

![image](https://user-images.githubusercontent.com/2825510/115290371-4be45e80-a108-11eb-8631-f5b6a7adc4ce.png)

**Comment by donaldthibeau** [comment]
This looks to be a support request, I would recommend emailing support@hedera.com

**Comment by ctapang** [comment]
I would advise against closing this issue. If it is a real technical issue, it should remain open, at least for historical record of a wallet that has now been discontinued.
