### ISSUE TITLE
Add getInfo call to the wallet

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-ios#33]
Also provide a non-technical description of the meaning.

For example, if the user is not the only controller of the account (e.g. the account is "one of two" keys to authorize transfers out), the user should see an alert.

Filed on behalf of the users of "ask-an-expert".  See conversations from Oct 13-14, 2019.

**Comment by avichalsaxena** [comment]
Duplicate #162
