### ISSUE TITLE
tools-ui: output the content of transaction files in a zip file into a csv file

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-ios#8]
- [x] output txs into a csv file
input: a  zip file which contains many tx files
output: a csv file which contains the content of transaction files in a zip file

- [x] verify signaturePair files
input: a zip file which contains many signaturePair files, a  zip file which contains many tx files, a public Key
output: a csv file which contains the content of transaction files in a zip file, and a column which indicates whether the signaturePair is valid or not

- [ ] verify signed transaction files
input: a zip file which contains many multi-signed transaction files, multiple pub key
output: a csv file which contains the content of transaction files in a zip file, and many columns which indicates whether a pub key has signed the transaction

**Comment by QianSwirlds** [comment]
@sreejithkaimal , this issue has been finished in September. I have confirmed with Oliver and that original issue has been closed.
